# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    # - run: whoami
    - run: npm i
    # - run: cp -r /home/admin/hubs-actions-runner/docs/backup/node_modules node_modules 
    # - run: ln -s /home/admin/hubs-actions-runner/docs/backup/node_modules node_modules 
    - run: npm run build
